vich_uploader:
  db_driver: orm
  metadata:
    auto_detection: true
    cache: file
    type: attribute
  mappings:
    covers:
      uri_prefix: '%cover_image%'
      upload_destination: '%kernel.project_dir%/public%cover_image%'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: false
      delete_on_remove: false